package View;

//Imports
import DAO.TarefaDAO;
import Model.Tarefas;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

public class MostraTarefa extends javax.swing.JFrame {

    //Instanciando Tela principal
    TelaPrincipal telaPrincipal = new TelaPrincipal();
    Tarefas tarefa = new Tarefas();

    //Atributos
    private Tarefas objetotarefas;

    //Construtor
    public MostraTarefa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTarefa = new javax.swing.JLabel();
        lblAtribuido = new javax.swing.JLabel();
        textFuncionario = new javax.swing.JTextField();
        c_tarefa = new javax.swing.JTextField();
        c_dadosTarefa = new javax.swing.JTextField();
        lblMarcaComo = new javax.swing.JLabel();
        radioPendente = new javax.swing.JRadioButton();
        radioResolvido = new javax.swing.JRadioButton();
        botaoVoltar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoDeletar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblDadosDaTarefa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numeroTarefa = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTarefa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTarefa.setText("Tarefa");

        lblAtribuido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAtribuido.setText("Atribuido para:");

        textFuncionario.setEditable(false);
        textFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFuncionarioActionPerformed(evt);
            }
        });

        c_tarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c_tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_tarefaActionPerformed(evt);
            }
        });
        c_tarefa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c_tarefaKeyPressed(evt);
            }
        });

        c_dadosTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMarcaComo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarcaComo.setText("Marcar como:");

        buttonGroup1.add(radioPendente);
        radioPendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioPendente.setText("Pendente");
        radioPendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPendenteActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioResolvido);
        radioResolvido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioResolvido.setText("Resolvido");

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoDeletar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoDeletar.setText("Deletar");
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tarefa:");

        lblDadosDaTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDadosDaTarefa.setText("Dados da tarefa:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nº da tarefa:");

        numeroTarefa.setEditable(false);
        numeroTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numeroTarefa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(c_dadosTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDadosDaTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAtribuido)
                                    .addComponent(jLabel4)
                                    .addComponent(textFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(c_tarefa))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(168, 168, 168)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioPendente)
                                            .addComponent(lblMarcaComo)
                                            .addComponent(jLabel1)
                                            .addComponent(radioResolvido)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addComponent(numeroTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSalvar)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(303, 303, 303))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtribuido)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(c_tarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDadosDaTarefa)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMarcaComo)
                        .addGap(10, 10, 10)
                        .addComponent(radioPendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioResolvido)
                        .addGap(26, 26, 26)))
                .addComponent(c_dadosTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoDeletar)
                    .addComponent(botaoSalvar))
                .addGap(39, 39, 39))
        );

        getAccessibleContext().setAccessibleName("Dados de tarefa");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Métodos
    private void textFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFuncionarioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textFuncionarioActionPerformed

    private void c_tarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_tarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_tarefaActionPerformed

    //configuração do botão de voltar
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void radioPendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPendenteActionPerformed

    //configuração do botão deletar
    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        //Confirmando a ação do usuario
        int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR esta tarefa ?");
        //Se clicar em sim vai carregar o if abaixo
        if (resposta_usuario == 0) {
            String numero = numeroTarefa.getText();
            int numerotarefa = Integer.parseInt(numero);

            if (this.tarefa.DeleteTarefaBD(numerotarefa)) {
                JOptionPane.showMessageDialog(rootPane, "Tarefa Apagada com Sucesso!");
            }
            //fecha a tela de mostrar tabela
            TelaPrincipal reload = new TelaPrincipal();
            reload.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_botaoDeletarActionPerformed

    //configuração do botão salvar
    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        //Atualiza o TarefaDao
        ArrayList<Tarefas> mostratarefa = new ArrayList<>();
        mostratarefa = TarefaDAO.Tabela;

        try {
            for (Tarefas a : mostratarefa) {
                int numerotarefa = Integer.parseInt(this.numeroTarefa.getText());
                String tarefa = "";
                String descricaotarefa = "";
                int id = a.getId();
                String nome = a.getNome();
                int idade = a.getIdade();
                String setor = a.getSetor();
                String turno = a.getTurno();
                String cpf = a.getCpf();
                String status = a.getStatus();

                if (this.c_tarefa.getText().length() <= 0) {
                    throw new Mensagens("Digite o titulo da tarefa");
                } else {
                    tarefa = this.c_tarefa.getText();
                }

                if (this.c_dadosTarefa.getText().length() <= 0) {
                    throw new Mensagens("Digite o que deve ser realizado");
                } else {
                    descricaotarefa = this.c_dadosTarefa.getText();
                }
                if (radioPendente.isSelected() == true) {
                    status = "Pendente";
                } else if (radioResolvido.isSelected() == true) {
                    status = "Resolvido";
                }

                //Atualiza TarefaDAO
                if (this.tarefa.UpdateTarefaBD(numerotarefa, tarefa, descricaotarefa, status, setor, cpf, turno, id, nome, idade)) {

                    
                }

            }

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número.");

        } finally {
            
        }
        JOptionPane.showMessageDialog(rootPane, "Tarefa atualizada");
        TelaPrincipal nova = new TelaPrincipal();
        this.setVisible(false);
        nova.setVisible(true);

    }//GEN-LAST:event_botaoSalvarActionPerformed

    //atalho para ir ao próximo campo dados tarefa
    private void c_tarefaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_tarefaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            c_dadosTarefa.requestFocus();
        }
    }//GEN-LAST:event_c_tarefaKeyPressed

    //Getters e setters 
    public JTextField getTextfuncionario() {
        return textFuncionario;
    }

    public void setTextfuncionario(JTextField c_funcionario) {
        this.textFuncionario = c_funcionario;
    }

    public JTextField getTextDadosDaTarefa() {
        return c_dadosTarefa;
    }

    public void setTextDadosDaTarefa(JTextField textDadosDaTarefa) {
        this.c_dadosTarefa = textDadosDaTarefa;
    }

    public JTextField getTextTarefa() {
        return c_tarefa;
    }

    public void setTextTarefa(JTextField textTarefa) {
        this.c_tarefa = textTarefa;
    }

    public JTextField getNumeroTarefa() {
        return numeroTarefa;
    }

    public void setNumeroTarefa(JTextField NumeroTarefa) {
        this.numeroTarefa = NumeroTarefa;
    }

    public JRadioButton getRadioPendente() {
        return radioPendente;
    }

    public void setRadioPendente(JRadioButton radioPendente) {
        this.radioPendente = radioPendente;
    }

    public JRadioButton getRadioResolvido() {
        return radioResolvido;
    }

    public void setRadioResolvido(JRadioButton radioResolvido) {
        this.radioResolvido = radioResolvido;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostraTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostraTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostraTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostraTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostraTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c_dadosTarefa;
    private javax.swing.JTextField c_tarefa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAtribuido;
    private javax.swing.JLabel lblDadosDaTarefa;
    private javax.swing.JLabel lblMarcaComo;
    private javax.swing.JLabel lblTarefa;
    private javax.swing.JTextField numeroTarefa;
    private javax.swing.JRadioButton radioPendente;
    private javax.swing.JRadioButton radioResolvido;
    private javax.swing.JTextField textFuncionario;
    // End of variables declaration//GEN-END:variables
}
